export const profileData = [
  {
    name: 'Aarav Sharma',
    age: 24,
    gender: 'Male',
    city: 'Delhi',
    profession: 'Software Engineer',
    hobbies: ['Coding', 'Gaming'],
    interests: ['Technology', 'Startups'],
    preferredActivities: ['Cafe hopping', 'Gaming sessions'],
    bio: 'Tech enthusiast who loves building cool projects and sipping black coffee.',
    lookingFor: 'Anyone'
  },
  {
    name: 'Ananya Gupta',
    age: 23,
    gender: 'Female',
    city: 'Delhi',
    profession: 'UI/UX Designer',
    hobbies: ['Photography', 'Reading'],
    interests: ['Art', 'Technology'],
    preferredActivities: ['Cafe hopping', 'Weekend trips'],
    bio: 'Passionate about minimalist design, photography, and finding hidden aesthetic cafes.',
    lookingFor: 'Both'
  },
  {
    name: 'Rohan Verma',
    age: 26,
    gender: 'Male',
    city: 'Delhi',
    profession: 'Data Analyst',
    hobbies: ['Cricket', 'Music'],
    interests: ['Technology', 'Movies'],
    preferredActivities: ['Playing cricket', 'Concerts'],
    bio: 'Numbers by day, music by night. Always down for a cricket match or live gig.',
    lookingFor: 'Female'
  },
  {
    name: 'Priya Singh',
    age: 25,
    gender: 'Female',
    city: 'Delhi',
    profession: 'Marketing Executive',
    hobbies: ['Dance', 'Travel'],
    interests: ['Movies', 'Cafes'],
    preferredActivities: ['Weekend trips', 'Cafe hopping'],
    bio: 'Lover of storytelling, spontaneous road trips, and exploring new food joints.',
    lookingFor: 'Male'
  },
  {
    name: 'Kabir Mehta',
    age: 27,
    gender: 'Male',
    city: 'Bengaluru',
    profession: 'Product Manager',
    hobbies: ['Hiking', 'Coding'],
    interests: ['Startups', 'Technology'],
    preferredActivities: ['Trekking', 'Networking meetups'],
    bio: 'Building products in Indias Silicon Valley. Loves weekend treks and tech banter.',
    lookingFor: 'Female'
  },
  {
    name: 'Diya Patel',
    age: 22,
    gender: 'Female',
    city: 'Bengaluru',
    profession: 'College Student',
    hobbies: ['Reading', 'Music'],
    interests: ['Books', 'Art'],
    preferredActivities: ['Book clubs', 'Cafe hopping'],
    bio: 'Literature student navigating life with acoustic music and a stack of books.',
    lookingFor: 'Male'
  },
  {
    name: 'Siddharth Rao',
    age: 29,
    gender: 'Male',
    city: 'Bengaluru',
    profession: 'Entrepreneur',
    hobbies: ['Running', 'Gaming'],
    interests: ['Startups', 'Fitness'],
    preferredActivities: ['Morning runs', 'Gaming sessions'],
    bio: 'Early stage founder working hard and staying active with marathons and gaming.',
    lookingFor: 'Anyone'
  },
  {
    name: 'Neha Joshi',
    age: 26,
    gender: 'Female',
    city: 'Bengaluru',
    profession: 'Product Designer',
    hobbies: ['Photography', 'Cooking'],
    interests: ['Art', 'Travel'],
    preferredActivities: ['Weekend trips', 'Cooking workshops'],
    bio: 'Designing digital experiences and experimenting with fusion recipes on weekends.',
    lookingFor: 'Both'
  },
  {
    name: 'Aditya Kulkarni',
    age: 28,
    gender: 'Male',
    city: 'Mumbai',
    profession: 'Photographer',
    hobbies: ['Photography', 'Hiking'],
    interests: ['Art', 'Movies'],
    preferredActivities: ['Photowalks', 'Sunset watching'],
    bio: 'Capturing moments across the city of dreams. Big cinema buff and sunset chaser.',
    lookingFor: 'Female'
  },
  {
    name: 'Meera Nair',
    age: 24,
    gender: 'Female',
    city: 'Mumbai',
    profession: 'Content Creator',
    hobbies: ['Dance', 'Cooking'],
    interests: ['Movies', 'Cafes'],
    preferredActivities: ['Cafe hopping', 'Dance rehearsals'],
    bio: 'Creating lifestyle content and hunting for the best filter coffee in Mumbai.',
    lookingFor: 'Male'
  },
  {
    name: 'Vikram Malhotra',
    age: 31,
    gender: 'Male',
    city: 'Mumbai',
    profession: 'Business Analyst',
    hobbies: ['Badminton', 'Reading'],
    interests: ['Books', 'Fitness'],
    preferredActivities: ['Badminton matches', 'Book clubs'],
    bio: 'Analytical mindset with a soft spot for classic literature and weekend badminton.',
    lookingFor: 'Female'
  },
  {
    name: 'Riya Sen',
    age: 25,
    gender: 'Female',
    city: 'Mumbai',
    profession: 'UI/UX Designer',
    hobbies: ['Art', 'Music'],
    interests: ['Technology', 'Cafes'],
    preferredActivities: ['Concerts', 'Cafe hopping'],
    bio: 'Designing intuitive interfaces, listening to indie pop, and exploring art galleries.',
    lookingFor: 'Anyone'
  },
  {
    name: 'Ayaan Khan',
    age: 23,
    gender: 'Male',
    city: 'Lucknow',
    profession: 'Developer',
    hobbies: ['Coding', 'Cricket'],
    interests: ['Technology', 'Startups'],
    preferredActivities: ['Playing cricket', 'Cafe hopping'],
    bio: 'Full-stack developer who appreciates good code, kebabs, and evening chai.',
    lookingFor: 'Female'
  },
  {
    name: 'Zoya Agarwal',
    age: 22,
    gender: 'Female',
    city: 'Lucknow',
    profession: 'Teacher',
    hobbies: ['Reading', 'Cooking'],
    interests: ['Books', 'Art'],
    preferredActivities: ['Book clubs', 'Weekend trips'],
    bio: 'Educator who loves history, heritage walks, and baking weekend treats.',
    lookingFor: 'Male'
  },
  {
    name: 'Samir Roy',
    age: 27,
    gender: 'Other',
    city: 'Lucknow',
    profession: 'Researcher',
    hobbies: ['Photography', 'Books'],
    interests: ['Art', 'Technology'],
    preferredActivities: ['Photowalks', 'Book clubs'],
    bio: 'Academic researcher exploring sociology, urban culture, and street photography.',
    lookingFor: 'Anyone'
  },
  {
    name: 'Ishaan Mishra',
    age: 25,
    gender: 'Male',
    city: 'Noida',
    profession: 'Software Engineer',
    hobbies: ['Gaming', 'Football'],
    interests: ['Technology', 'Fitness'],
    preferredActivities: ['Gaming sessions', 'Football matches'],
    bio: 'Competitive gamer and software dev who never misses a weekend football match.',
    lookingFor: 'Female'
  },
  {
    name: 'Kavya Srivastava',
    age: 24,
    gender: 'Female',
    city: 'Noida',
    profession: 'Data Analyst',
    hobbies: ['Dancing', 'Travel'],
    interests: ['Cafes', 'Movies'],
    preferredActivities: ['Weekend trips', 'Cafe hopping'],
    bio: 'Turning complex data into insights. Travel lover seeking new adventures.',
    lookingFor: 'Male'
  },
  {
    name: 'Alex Dsouza',
    age: 26,
    gender: 'Other',
    city: 'Noida',
    profession: 'Content Creator',
    hobbies: ['Music', 'Art'],
    interests: ['Movies', 'Technology'],
    preferredActivities: ['Concerts', 'Photowalks'],
    bio: 'Digital storyteller passionate about indie music, digital art, and pop culture.',
    lookingFor: 'Both'
  },
  {
    name: 'Devendra Pandey',
    age: 30,
    gender: 'Male',
    city: 'Gurugram',
    profession: 'Product Manager',
    hobbies: ['Running', 'Reading'],
    interests: ['Startups', 'Books'],
    preferredActivities: ['Morning runs', 'Networking meetups'],
    bio: 'Corporate strategist by day, avid reader and distance runner by dawn.',
    lookingFor: 'Female'
  },
  {
    name: 'Tanvi Kapoor',
    age: 27,
    gender: 'Female',
    city: 'Gurugram',
    profession: 'Marketing Executive',
    hobbies: ['Cooking', 'Fitness'],
    interests: ['Travel', 'Cafes'],
    preferredActivities: ['Cafe hopping', 'Gym sessions'],
    bio: 'Brand marketer into fitness, healthy cooking, and discovering aesthetic cafes.',
    lookingFor: 'Male'
  },
  {
    name: 'Harsh Vardhan',
    age: 28,
    gender: 'Male',
    city: 'Gurugram',
    profession: 'Entrepreneur',
    hobbies: ['Hiking', 'Gaming'],
    interests: ['Technology', 'Startups'],
    preferredActivities: ['Trekking', 'Gaming sessions'],
    bio: 'Tech startup founder who balances long work hours with mountain treks.',
    lookingFor: 'Both'
  },
  {
    name: 'Sneha Deshmukh',
    age: 26,
    gender: 'Female',
    city: 'Pune',
    profession: 'Software Engineer',
    hobbies: ['Coding', 'Badminton'],
    interests: ['Technology', 'Fitness'],
    preferredActivities: ['Badminton matches', 'Weekend trips'],
    bio: 'Backend dev loving Punes pleasant weather, badminton, and road trips.',
    lookingFor: 'Male'
  },
  {
    name: 'Chaitanya Shinde',
    age: 25,
    gender: 'Male',
    city: 'Pune',
    profession: 'UI/UX Designer',
    hobbies: ['Photography', 'Music'],
    interests: ['Art', 'Movies'],
    preferredActivities: ['Photowalks', 'Concerts'],
    bio: 'Visual designer exploring street photography and live indie music gigs.',
    lookingFor: 'Female'
  },
  {
    name: 'Varun Reddy',
    age: 27,
    gender: 'Male',
    city: 'Hyderabad',
    profession: 'Developer',
    hobbies: ['Cricket', 'Gaming'],
    interests: ['Technology', 'Startups'],
    preferredActivities: ['Playing cricket', 'Gaming sessions'],
    bio: 'Full-stack coder, weekend cricket captain, and avid gamer living in Hyderabad.',
    lookingFor: 'Anyone'
  }
];
